jobs/urls.py
from django.urls import path
from .views import AllJobListView, JobCreateView, JobUpdateView, JobDeleteView, JobDetailView

urlpatterns = [
    # list jobs view
    path('', AllJobListView.as_view(), name='list_jobs'),

    # job detail view
    path('<int:pk>/', JobDetailView.as_view(), name='job_detail'),

    # update job view
    path('update/<int:pk>/', JobUpdateView.as_view(), name='update_job'),

    # delete job view
    path('delete/<int:pk>/', JobDeleteView.as_view(), name='delete_job'),
]

resumes/urls.py
from django.urls import path
from .views.education_views import AddEducationView, DeleteEducationView, EditEducationView

from .views.job_applicant_views import MyApplicantProfilesListView, JobApplicantCreateView, JobApplicantUpdateView, JobApplicantDeleteView
from .views.work_experience_views import AddExperienceView, DeleteExperienceView, EditExperienceView
from .views.resume_detail_view import ResumeDetailView

# add the routes for the views here

urlpatterns = [
    path('', MyApplicantProfilesListView.as_view(), name='my_resumes_list'),
    path('create/', JobApplicantCreateView.as_view(), name='my_resumes_create'),
    path('create/<int:pk>/edit/', JobApplicantUpdateView.as_view(), name='my_resumes_edit'),
    path('create/<int:pk>/delete/', JobApplicantDeleteView.as_view(), name='my_resumes_delete'),
    
    # resume detail
    path('detail/<int:resume_pk>/', ResumeDetailView.as_view(), name='my_resumes_detail'),

    # add the routes for the experience views
    path('create/<int:resume_pk>/add-experience/', AddExperienceView.as_view(), name='my_resumes_add_experience'),
    path('create/<int:resume_pk>/add-experience/<int:experience_pk>/delete/', DeleteExperienceView.as_view(), name='my_resumes_delete_experience'),
    path('create/<int:resume_pk>/add-experience/<int:experience_pk>/edit/', EditExperienceView.as_view(), name='my_resumes_edit_experience'),

    path('create/<int:resume_pk>/add-education/', AddEducationView.as_view(), name='my_resumes_add_education'),
    # path('create/<int:resume_pk>/add-education/', EducationCreateView.as_view(), name='my_resumes_add_education'),
    path('create/<int:resume_pk>/add-education/<int:education_pk>/delete/', DeleteEducationView.as_view(), name='my_resumes_delete_education'),
    path('create/<int:resume_pk>/add-education/<int:education_pk>/edit/', EditEducationView.as_view(), name='my_resumes_edit_education'),
]

website/urls.py
from django.views.generic import TemplateView
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from users.views import UserLoginView, UserRegisterView, UserLogoutView, DummyLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    
    # the user routes
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    # dummy login
    path('dummy-login/', DummyLoginView.as_view(), name='dummy-login'),

    # app routes
    path('profile/', include('users.urls')),
    path('companies/', include('companies.urls')),
    path('jobs/', include('jobs.urls')),
    path('resumes/', include('resumes.urls')),
    path('applications/', include('applications.urls')),

    # django browser reload
    path("__reload__/", include("django_browser_reload.urls")),

    # text editor import
    path('tinymce/', include('tinymce.urls')),

    # error pages
    path('error/', TemplateView.as_view(template_name='error.html'), name='error'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

resumes/models.py
from django.db import models
from users.models import CustomUser
from django.contrib.postgres.fields import ArrayField

class Resume(models.Model):
    
    title = models.CharField(max_length=100, verbose_name='Title')
    user_owner = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        default=0,
    )

    def __str__(self):
        return f"{self.title}"
    


class Experience(models.Model):
    term = models.CharField(max_length=50, verbose_name='Term')
    title = models.CharField(max_length=100, verbose_name='Job Title')
    company = models.CharField(max_length=100, verbose_name='Institution')

    def __str__(self):
        return f"{self.title} at {self.company} during the term {self.term}"
    
class Education(models.Model):
    term = models.CharField(max_length=50, verbose_name='Term')
    title = models.CharField(max_length=100, verbose_name='Job Title')
    institution = models.CharField(max_length=100, verbose_name='Institution')


    def __str__(self):
        return f"{self.title} at {self.institution} during the term {self.term}"

class JobApplicant(models.Model):
    title = models.CharField(max_length=100, verbose_name='Title')
    resume_file = models.FileField(upload_to='resumes/uploads/', verbose_name='Resume File')

    user_owner = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        default=0,
        related_name='job_applicant_profile'
    )

    education = models.ManyToManyField(
        Education,
        verbose_name='Education',
        blank=True
    )

    experience = models.ManyToManyField(
        Experience,
        verbose_name='Work Experience',
        blank=True
    )
    
    skills = ArrayField(
        models.CharField(max_length=50, blank=True),
        verbose_name='Skills',
        blank=True,
        null=True
    )

    def __str__(self):
        return f"{self.title} - {self.resume_file.name.split('/')[-1]}"

    class Meta:
        verbose_name = 'Job Applicant'
        verbose_name_plural = 'Job Applicants'

resumes/forms.py
from django import forms
from .models import JobApplicant, Resume, Education, Experience
from django.forms import formset_factory

class ResumeForm(forms.ModelForm):
    class Meta:
        model = Resume
        fields = ['title']

class ExperienceForm(forms.ModelForm):
    class Meta:
        model = Experience
        fields = ['term', 'title', 'company']

class EducationForm(forms.ModelForm):
    class Meta:
        model = Education
        fields = ['term', 'title', 'institution']

ExperienceFormSet = formset_factory(ExperienceForm, extra=1)
EducationFormSet = formset_factory(EducationForm, extra=1)

class JobApplicantForm(forms.ModelForm):
    skills = forms.CharField(widget=forms.TextInput(attrs={'class': 'skill-input'}), required=False)

    # allow to create a new resume, experience, and education on job applicant creation
    resume = ResumeForm()
    
    class Meta:
        model = JobApplicant
        # fields = ['title', 'resume_file', 'skills']
        fields = ['title', 'resume_file', 'skills']

resumes/views/education_views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from resumes.models import JobApplicant, Education
from django.views import View
from resumes.forms import EducationForm



# education templates
class AddEducationView(View, LoginRequiredMixin):
    def get(self, request, resume_pk):
        # use the pk from the url to find the JobApplicant object
        job_applicant = JobApplicant.objects.get(pk=resume_pk)

        # find other experiences associated with this job applicant
        educations = job_applicant.education.all()

        # verify that user is the owner of the job applicant profile
        if job_applicant.user_owner != request.user:
            return redirect('my_resumes_add_education', resume_pk=resume_pk)

        # add the form to the context
        context = {
            'form': EducationForm(),
            'job_applicant': job_applicant,
            'educations': educations,
        }
        
        return render(request, 'my_resume_add_education.html', context)
    
    def post(self, request, resume_pk):
        # use the pk from the url to find the JobApplicant object
        job_applicant = JobApplicant.objects.get(pk=resume_pk)

        # find other experiences associated with this job applicant
        educations = job_applicant.education.all()

        # add the form to the context
        context = {
            'form': EducationForm(),
            'job_applicant': job_applicant,
            'educations': educations,
        }

        # create the form from the post data
        form = EducationForm(request.POST)

        # validate the form
        if form.is_valid():
            # save the form
            education = form.save()
            # add the experience to the job applicant
            job_applicant.education.add(education)
            # reload the page
            return redirect('my_resumes_add_education', resume_pk=resume_pk)
        
        # re-render site
        return render(request, 'my_resume_add_education.html', context)

# the following is a class based view to delete an education
class DeleteEducationView(View, LoginRequiredMixin):
        
    
    def post(self, request, resume_pk, education_pk):
        """ delete the education """
        # use the pk from the url to find the JobApplicant object
        job_applicant = JobApplicant.objects.get(pk=resume_pk)

        # find the education to delete
        education = Education.objects.get(pk=education_pk)

        # find other educations associated with this job applicant
        educations = job_applicant.education.all()

        # verify that the job education has foreign key education, if not return bad request
        if education not in job_applicant.education.all():
            return redirect('my_resumes_add_education', resume_pk=resume_pk)
        
        # if user owner not the same as the current user, unauthorized, 
        # for now it only will redirect to the same page
        if job_applicant.user_owner != request.user:
            return redirect('my_resumes_add_education', resume_pk=resume_pk)

        # delete the education
        education.delete()

        # reload the page
        return redirect('my_resumes_add_education', resume_pk=resume_pk)

class EditEducationView(View, LoginRequiredMixin):
    # get the view template for edit
    def get(self, request, resume_pk, education_pk):
        """ get the edit template """
        # use the pk from the url to find the JobApplicant object
        job_applicant = JobApplicant.objects.get(pk=resume_pk)

        # find the education to delete
        current_education = Education.objects.get(pk=education_pk)

        # find other educations associated with this job applicant
        educations = job_applicant.education.all()

        # verify that the job education has foreign key education, if not return bad request
        if current_education not in job_applicant.education.all():
            return redirect('my_resumes_add_education', resume_pk=resume_pk)
        
        # if user owner not the same as the current user, unauthorized, 
        # for now it only will redirect to the same page
        if job_applicant.user_owner != request.user:
            return redirect('my_resumes_add_education', resume_pk=resume_pk)

        # add the form to the context
        context = {
            'form': EducationForm(
                initial={
                    'term': current_education.term,
                    'title': current_education.title,
                    'institution': current_education.institution,
                }
            ),
            'job_applicant': job_applicant,
            'educations': educations,
            'edit_form': True,
        }

        return render(request, 'my_resume_add_education.html', context)
    
    # edit the view
    def post(self, request, resume_pk, education_pk):
        """ edit the education """
        # use the pk from the url to find the JobApplicant object
        job_applicant = JobApplicant.objects.get(pk=resume_pk)

        # find the education to edit
        education = Education.objects.get(pk=education_pk)

        # verify that the job education has foreign key education, if not return bad request
        if education not in job_applicant.education.all():
            return redirect('my_resumes_add_education', resume_pk=resume_pk)
        
        # if user owner not the same as the current user, unauthorized, 
        # for now it only will redirect to the same page
        if job_applicant.user_owner != request.user:
            return redirect('my_resumes_add_education', resume_pk=resume_pk)
        
        # edit the education
        education.term = request.POST['term']
        education.title = request.POST['title']
        education.institution = request.POST['institution']

        # save the education
        education.save()

        # reload the page
        return redirect('my_resumes_add_education', resume_pk=resume_pk)
    

resumes/views/job_applicant_views.py
# pylint: disable=too-many-ancestors
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from resumes.models import JobApplicant
from django.views.generic.edit import CreateView
from django.views import View
from django.views.generic.edit import UpdateView
from django.urls import reverse


# get all my owned job applicant profiles
class MyApplicantProfilesListView(ListView, LoginRequiredMixin):
    """ Renders a list of all Job Applicant Profiles."""
    model = JobApplicant
    template_name = 'my_resumes_list.html'
    context_object_name = 'job_applicant'
    
    def get_queryset(self):
        # print(self.request.user)
        # print(JobApplicant.objects.filter(user_owner=self.request.user))
        return JobApplicant.objects.filter(user_owner=self.request.user)
        
    

# job applicant profiles consist of the following steps.
# 1. create a resume: job applicant profile
# 2. add experience to the job applicant profile, each in its own post form
# 3. add education to the job applicant profile, each in its own post form

class JobApplicantCreateView(CreateView, LoginRequiredMixin):
    """ Renders a form to create a new Job Applicant Profile."""
    model = JobApplicant
    fields = ['title', 'resume_file', 'skills']
    template_name = 'my_resumes_create.html'
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        # add user_owner to the form
        form.instance.user_owner = self.request.user
        context = self.get_context_data()
        

        if form.is_valid():

            # validate that resume file can only accept pdf files
            if form.cleaned_data['resume_file'].content_type != 'application/pdf':
                context['form'] = form
                # add errors to the context array
                context['errors'] = ['Resume file must be a pdf file']
                return render(self.request, 'my_resumes_create.html', context)
            
            
            # save the form
            self.object = form.save()
            # add the model object pk and redirect to the add experience view
            return redirect('my_resumes_add_experience', resume_pk=self.object.pk)

        return super().form_valid(form)
    
class JobApplicantUpdateView(UpdateView, LoginRequiredMixin):
    """ Renders a form to update a Job Applicant Profile."""
    model = JobApplicant
    fields = ['title', 'resume_file', 'skills']
    template_name = 'my_resumes_create.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['job_applicant'] = JobApplicant.objects.get(pk=self.kwargs['pk'])
        return context
    
    def form_valid(self, form):
        # add user_owner to the form
        form.instance.user_owner = self.request.user
        context = self.get_context_data()
        

        if form.is_valid():

            # because we are uploading a form, them we have to do a try catch
            try:
                # verify if there is a new resume_file in the form
                if form.cleaned_data['resume_file'].content_type != 'application/pdf':
                    context['form'] = form
                    # add errors to the context array
                    context['errors'] = ['Resume file must be a pdf file']
                    return render(self.request, 'my_resumes_create.html', context)
            except AttributeError:
                # do nothing, because the user did not upload a new resume file
                pass
            # save the form
            self.object = form.save()
            # add the model object pk and redirect to the add experience view
            return redirect('my_resumes_add_experience', resume_pk=self.object.pk)

        return super().form_valid(form)

class JobApplicantDeleteView(View, LoginRequiredMixin):
    """ Renders a form to delete a Job Applicant Profile."""
    def post(self, request, pk):
        # find the job applicant
        job_applicant = JobApplicant.objects.get(pk=pk)
        # verify that the user is the owner of the job applicant
        if job_applicant.user_owner != request.user:
            # add error 
            return redirect(reverse('my_resumes_list'), kwargs={'errors': ['You are not authorized to delete this job applicant profile']})
        

        # delete the job applicant
        job_applicant.delete()
        # redirect to the job applicant list
        return redirect('my_resumes_list')

    

resumes/templates/my_resume_add_education.html
{% extends 'layout.html' %}
{% load static %}


{% block title %}
  Add Education
{% endblock title %}

<!-- load crispy forms -->
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% load crispy_forms_filters %}

{% block content %}

  <main class="max-w-4xl p-8 mx-auto my-6 flex flex-col gap-8  ">
    <h1 class="text-3xl my-6 font-bold text-center text-slate-600" >Add Education</h1>
    
    <table class="table-auto">
        <thead class="text-left border-b-2 border-slate-800">
            <tr class="">
                <th class="">Term</th>
                <th class="">Title</th>
                <th class="">Company</th>
                <th>Options</th>
            </tr>
        </thead>

        {% for ed in educations %}
            <tr class="">
                
                <td class="">{{ ed.term }}</td>
                <td class="">{{ ed.title }}</td>
                <td class="">{{ ed.institution }}</td>
                <td class="flex flex-row">
                    <form action="/resumes/create/{{job_applicant.id}}/add-education/{{ed.id}}/delete/" method="POST">
                        {% csrf_token %}
                        <button type="submit" class=" bg-red-500 text-white px-6 py-1 rounded-lg ">Delete</button>
                    </form>

                    <a href="/resumes/create/{{job_applicant.id}}/add-education/{{ed.id}}/edit/" class="mx-3 bg-emerald-500 text-white px-6 py-1 rounded-lg ">Edit</a>
                </td>
            </tr>
        {% endfor %}
        </table>

    <!-- the add new work education form -->
    <form method="POST" enctype="multipart/form-data" id="education-form" class=" flex flex-col gap-6 ">
        {% csrf_token %}
        
        {% if form.errors %}
          <p class="text-red-500 text-xs italic">Please fix the errors below.</p>
        {% endif %}

        <div class="education-form">
            {{ form.term|as_crispy_field }}
            {{ form.title|as_crispy_field }}
            {{ form.institution|as_crispy_field }}
        </div>

        {% if edit_form %}
        <div class="mx-auto ">
            <button type="submit" id="edit-education" class="bg-emerald-500 mx-2 text-white px-6 py-1 rounded-lg">Edit Education</button>
            <button type="button" id="edit-education" class="bg-purple-500 mx-2 text-white  rounded-lg px-6 py-1" ><a href="/resumes/create/{{job_applicant.id}}/add-education/">Add New Education</a></button>
        </div>

        {% else %}
            <button type="submit" id="add-education" class="bg-emerald-500 text-white px-6 py-1 mx-auto rounded-lg">Add Education</button>
        {% endif %}

    </form>

    <!-- the prev next navigate -->
    <div class="my-4 flex flex-row gap-6 justify-center">
        <button type="button" class="bg-purple-500 text-white px-6 py-1 rounded-lg "><a href="{% url 'my_resumes_add_experience' job_applicant.id %}">Previous</a></button>
        <button type="button" class="bg-purple-500 text-white px-6 py-1 rounded-lg "><a href="{% url 'my_resumes_list' %}">Next</a></button>
    </div>
    

  </main>
{% endblock content %}
  

resumes/templates/my_resume_add_work_experience.html
{% extends 'layout.html' %}
{% load static %}


{% block title %}
  Add Experience
{% endblock title %}

<!-- load crispy forms -->
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% load crispy_forms_filters %}

{% block content %}

  <main class="max-w-4xl p-8 mx-auto my-6 flex flex-col gap-8  ">
    <h1 class="text-3xl my-6 font-bold text-center text-slate-600" >Add Experience</h1>
    
    <table class="table-auto">
        <thead class="text-left border-b-2 border-slate-800">
            <tr class="">
                <th class="">Term</th>
                <th class="">Title</th>
                <th class="">Company</th>
                <th>Options</th>
            </tr>
        </thead>

        {% for exp in experiences %}
            <tr class="">
                <td class="">{{ exp.term }}</td>
                <td class="">{{ exp.title }}</td>
                <td class="">{{ exp.company }}</td>
                <td class="flex flex-row">
                    <form action="/resumes/create/{{job_applicant.id}}/add-experience/{{exp.id}}/delete/" method="POST">
                        {% csrf_token %}
                        <button type="submit" class=" bg-red-500 text-white px-6 py-1 rounded-lg ">Delete</button>
                    </form>

                    <a href="/resumes/create/{{job_applicant.id}}/add-experience/{{exp.id}}/edit/" class="mx-3 bg-emerald-500 text-white px-6 py-1 rounded-lg ">Edit</a>
                </td>
            </tr>
        {% endfor %}
        </table>

    <!-- the add new work experience form -->
    <form method="POST" enctype="multipart/form-data" id="experience-form" class=" flex flex-col gap-6 ">
        {% csrf_token %}
        
        {% if errors %}
          <p class="text-red-500 text-xs italic">Please fix the errors below.</p>
        {% endif %}

        <div class="experience-form">
            {{ form.term|as_crispy_field }}
            {{ form.title|as_crispy_field }}
            {{ form.company|as_crispy_field }}
        </div>

        {% if edit_form %}
        <div class="mx-auto ">
            <button type="submit" id="edit-experience" class="bg-emerald-500 mx-2 text-white px-6 py-1 rounded-lg">Edit Experience</button>
            <button type="button" id="edit-experience" class="bg-purple-500 mx-2 text-white  rounded-lg px-6 py-1" ><a href="/resumes/create/{{job_applicant.id}}/add-experience/">Add New Experience</a></button>
        </div>

        {% else %}
            <button type="submit" id="add-experience" class="bg-emerald-500 text-white px-6 py-1 mx-auto rounded-lg">Add Experience</button>
        {% endif %}

    </form>

    <!-- the prev next navigate -->
    <div class="my-4 flex flex-row gap-6 justify-center">
        <button type="button" class="bg-purple-500 text-white px-6 py-1 rounded-lg "><a href="{% url 'my_resumes_create' %}">Previous</a></button>
        <button type="button" class="bg-purple-500 text-white px-6 py-1 rounded-lg "><a 
            href="{% url 'my_resumes_add_education' job_applicant.id %}"
            >Next</a></button>
    </div>
    

  </main>
{% endblock content %}
  

resumes/templates/my_resumes_create.html
{% extends 'layout.html' %}
{% load static %}


{% block title %}
  Create a Resume Profile
{% endblock title %}

<!-- load crispy forms -->
{% load crispy_forms_tags %}
{% load crispy_forms_field %}
{% load crispy_forms_filters %}

{{ form.media }}


{% block content %}

  <main class="max-w-4xl p-8 mx-auto my-6 flex flex-col gap-12 ">
    <h1 class="text-3xl font-bold text-center text-slate-600" >Create a Resume</h1>

    <form action="" method="POST" enctype="multipart/form-data" class="my-12 flex flex-col gap-6 ">
        {% csrf_token %}

        <!-- add form invalid message -->
        {% if errors %}
            <!-- iterate the errors -->
            {% for error in errors %}
                <p class="text-red-500 text-xs italic">{{ error }}</p>
            {% endfor %}
        {% endif %}

        <!-- add the job_applicant context if exist -->
        <div class="flex flex-col" >
            <label for="title" class="font-bold">Title*</label>
            <input type="text" name="title" id="title" class="border-2 rounded-lg border-slate-800 px-4 py-1" placeholder="Enter a title"
            {% if job_applicant %}
              value="{{ job_applicant.title }}"
            {% endif %}
            >
        </div>

        <div class="flex flex-col" >
            <label for="resume_file" class="font-bold">Resume File*</label>
            <input type="file" name="resume_file" id="resume_file" class="border-2 rounded-lg border-slate-800 px-4 py-1" placeholder="Enter a title"
            >
            <!-- show file name if in context -->
            {% if job_applicant %}
              <p class="text-lg text-slate-600 break-all">{{ job_applicant.resume_file }}</p>
            {% endif %}
        </div>
        
        <div>
            <label for="skills" class="font-bold">Skills*</label>
            <div id="skills-container" class="flex flex-row gap-4 flex-wrap items-center ">
                <input type="text" name="skills" id="skills" class="skill-input border-2 rounded-lg border-slate-800 px-4 py-1" placeholder="Enter a skill and press Add">
                <button type="button" id="add-skill" class="bg-emerald-600 text-white px-4 py-1 rounded-lg">Add Skill</button>
                <button type="button" id="drop-all-skills" class="bg-red-500 text-white px-4 py-1 rounded-lg">Drop All Skills</button>
                <i id="skill-error-msg" class="text-red-500 "></i>
            </div>
            <div id="skills-bank-container" class="flex flex-row flex-wrap gap-4">
                
                
            </div>
        </div>

        <!-- make a hidden p with the skills list -->
        <p id="skills-list" class="">{{ job_applicant.skills }}</p>
            
        <button type="submit" class="bg-purple-500 text-white px-6 py-1 rounded-lg mx-auto self-center ">Next</button>
    </form>
    

  </main>

  
    <script>
        $(document).ready(function() {
            let skillList = [];

            
            function repopulateSkills() {
                // clear the skills-bank-container
                $('#skills-bank-container').empty();

                // add the skills to the skills-bank-container
                skillList.forEach(skill => {
                    $('#skills-bank-container').append(`<button type="button" class="text-white bg-slate-400 px-4 py-1 rounded-lg skill-card">${skill}</button>`);
                });
            }



            $('#add-skill').click(function() {
                const skillInput = $('#skills').val();
                $('#skill-error-msg').text('');

                // if the user didn't enter anything, then show an error message
                if (skillInput === '') {
                    $('#skill-error-msg').text('Please enter a skill');
                    return;
                }
                // separate the skills into an array by comma
                let skills = skillInput.split(',');

                // remove any whitespace from the skills
                skills = skills.map(skill => skill.trim());

                // capitalize the first letter each word in the skills array
                skills = skills.map(skill => {
                    return skill.split(' ').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');
                });

                // remove any of the skills that are already in the skillList
                skills = skills.filter(skill => !skillList.includes(skill));

                
                // if there are no skills left, then the user entered a skill that is already in the list
                if (skills.length === 0) {
                    $('#skill-error-msg').text('Please enter a skill that is not already in the list');
                    return;
                }

                // merge skills into skillList
                skillList = skillList.concat(skills);

                repopulateSkills();


                // clear the input field
                $('#skills').val('');

                // set the focus on the skills input field
                $('#skills').focus();
            });

            // remove all skills from the skillList
            $('#drop-all-skills').click(function() {
                // clear the input and output field
                $('#skill-error-msg').text('');
                $('#skills').val('');
                $('#skills').focus();

                skillList = [];
                repopulateSkills();
            });

            $('form').submit(function() {
                // add the skills to the form request
                
                // prepare and send the form to the serv3er
                $.ajax({
                    type: 'POST',
                    url: '',
                    data: {
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                        'title': $('#id_title').val(),
                        'resume_file': $('#id_resume_file').val(),
                        'skills': skillList,
                    },
                    success: function(response) {
                        console.log('success');
                    },
                    error: function(response) {
                        console.log("error");
                    }
                });
            });

            

            
        });
    </script>
{% endblock content %}
  